---
swagger: "2.0"
info:
  description: "API to login to HPE with Username and PAssword"
  version: "1.0.0"
  title: "HPE Login API"
  contact:
    email: "kollisreekanth@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "virtserver.swaggerhub.com"
basePath: "/ADP9529/hpe/1.0.0"
tags:
- name: "HPE User"
  description: "Secured Login"
schemes:
- "https"
paths:
  /logintest:
    post:
      tags:
      - "HPE User"
      summary: "Validates the username and password"
      description: "Validates the username and passwrod against the users in the system"
      operationId: "login"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "User"
        description: "user to validate"
        required: false
        schema:
          $ref: "#/definitions/User"
        x-exportParamName: "User"
      responses:
        "200":
          description: "User validated"
        "400":
          description: "invalid input, object invalid"
        "404":
          description: "User not found"
definitions:
  User:
    type: "object"
    required:
    - "password"
    - "username"
    properties:
      id:
        type: "string"
        format: "uuid"
        example: "d290f1ee-6c54-4b01-90e6-d701748f0851"
      username:
        type: "string"
        example: "user1"
      password:
        type: "string"
        example: "password"
      createdDate:
        type: "string"
        format: "date-time"
        example: "2016-08-29T09:12:33.001+0000"
    example:
      password: "password"
      createdDate: "2016-08-29T09:12:33.001+0000"
      id: "d290f1ee-6c54-4b01-90e6-d701748f0851"
      username: "user1"
