/*
 * HPE Login API
 *
 * API to login to HPE with Username and PAssword
 *
 * API version: 1.0.0
 * Contact: kollisreekanth@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type User struct {

	Id string `json:"id,omitempty"`

	Username string `json:"username"`

	Password string `json:"password"`

	CreatedDate time.Time `json:"createdDate,omitempty"`
}
